<template>
  <v-container fluid class='RogueComponent'>
    <v-slide-y-transition mode='out-in'>
      <v-layout column align-center>
        <v-avatar class='hidden-sm-and-down' size='172px' >
          <img src='../assets/img/Logo-192x192.svg' alt='Rogue Designs'>
        </v-avatar>
        <v-avatar class='hidden-md-and-up' size='84px' >
          <img src='../assets/img/Logo-192x192.svg' alt='Rogue Designs'>
        </v-avatar>
          <p class='headline'>Rogue Designs</p>
          <p class='title'>Affordable Computer Services</p>        
      </v-layout>
    </v-slide-y-transition>
    <v-layout column class='RogueLayout'>
      <v-flex xs12 sm12 md8 lg6 xl6>
        <v-toolbar color='primary'>
          <v-toolbar-title class='white--text RogueToolbarTitle title'>RaspberryPi Images</v-toolbar-title>
        </v-toolbar>
        <v-card>
          <v-card-title class='title'>VPN</v-card-title>
            <ul class='subheading RogueUL' style='list-style-type:disc'>
              <li><p>Uses OpenVPN to establish a secure connection to any site you wish to go to. Tunnels trough with https so less of a chance of ISP discovering you are using a VPN.</p></li>
              <li><p>No month cost, OpenVPN certificates are generated by the RaspberryPi.</p></li>
              <li><p>With the FCC deregulating the ISP's, the only way to insure the same connection to your favorite websites is with a VPN (Virtual Private Network). VPN's protect you from being observed from your ISP or any hackers on the internet.</p></li>
            </ul>
          <v-card-actions class='RogueCardActions'>
            <v-btn round dark small color='primary' @click='$router.push("/contact")'>Contact</v-btn>
          </v-card-actions>
          <v-divider></v-divider>
          <v-card-title class='title'>Media Server</v-card-title>
            <ul class='subheading RogueUL' style='list-style-type:disc'>
              <li><p>Can be installed with Plex Media Server or Open Media Server. Automatically, catalog and watch all your media. Can be connected to any external USB Drive.</p></li>
              <li><p>Plex and Open Media Server can use DLNA to stream your media.</p></li>
            </ul>
          <v-card-actions class='RogueCardActions'>
            <v-btn dark round color='primary' @click='$router.push("/contact")'>Contact</v-btn>
          </v-card-actions>
          <v-divider></v-divider>
          <v-card-title class='title'>Web Server</v-card-title>

            <ul class='RogueUL subheading' style='list-style-type:disc'>
              <li><p>Run your own Web Server and cut your monthly costs of GoDaddy!</p></li>
              <li><p>Plex and Open Media Server can use DLNA to stream your media.</p></li>
              <li><p>Stream your media collection anywhere you have a internet connection.</p></li>
            </ul>

          <v-card-actions class='RogueCardActions'>
            <v-btn dark round color='primary' @click='$router.push("/contact")'>Contact</v-btn>
          </v-card-actions>
          <v-divider></v-divider>
          <v-card-title class="title">Proxy Server</v-card-title>

            <ul class='subheading RogueUL' style='list-style-type:disc'>
              <li><p>Setup a proxy server to block ads, track internet usage. Setup Blacklists to prevent children from seeing adult content.</p></li>
            </ul>

          <v-card-actions class='RogueCardActions'>
            <v-btn dark round color='primary' @click='$router.push("/contact")'>Contact</v-btn>
          </v-card-actions>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>

export default {
  name: 'raspberrypi',
  data () {
    return {
      msg: 'Raspberrypi.vue'
    }
  }
}
</script>

<!-- Add 'scoped' attribute to limit CSS to this component only -->
<style scoped>

</style>
